services:
  my-profile-web:
    build: .
    ports:
      - "8080:80"
    restart: always
  todo-app:
    image: nginx:alpine
    volumes:
      - ./todo-static:/usr/share/nginx/html
    ports:
      - "8081:80"
    restart: always