name: Auto Deploy to AWS EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository code
        uses: actions/checkout@v4
      - name: Connect EC2 & update project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Lab12-Final-Project
            git pull
            docker-compose down
            docker-compose up -d --build